name: Update version
on:
  push:
    paths:
      - 'README.md'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.0.0
    - uses: actions/checkout@v3
    - run: |
        date > generated.txt
        helmfile version
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
