name: Update version
on:
  push:
    paths:
      - 'README.md'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.0.0
    - name: Generate file
      run: |
        echo "text" > test.md
    - name: GIT commit and push all changed files
      env:
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit --amend --no-edit
        git push -f
